In [627]:
import numpy as np
import pandas as pd

22.75

In [64]:
num = 10000
num_asset = 2
num_time_step = 32
r = 0.03/365
rho = 0.2
sigma1 = 0.3
sigma2 = 0.4

In [67]:
st = 100

In [68]:
tmp = np.ones((num, num_time_step))
#np.random.normal()
T = 1/32

x1 = np.random.normal(size=(num, num_time_step))
x2 = rho * x1 + np.random.normal(size=(num, num_time_step)) * np.sqrt(1 - rho**2)

100 * np.exp((r - 0 - 0.5*(sigma1**2)) * T + sigma1 * np.sqrt(T) * x1)

array([[ 91.87354003, 101.42121785,  95.91510448, ...,  98.86480675,
        107.42741119, 101.09606959],
       [104.20359527,  90.80284995,  93.26753579, ...,  98.47577363,
        101.17230908, 114.26955268],
       [ 95.43216872,  96.97049391,  95.08980086, ...,  92.45015272,
         98.41193156, 103.99978691],
       ...,
       [ 91.95207732,  98.20270227,  98.0154752 , ..., 101.43164397,
        105.46354898, 104.99837902],
       [ 91.71889124, 102.46133587, 105.1342564 , ..., 108.9559244 ,
        104.78297289,  97.74960125],
       [ 94.853572  ,  92.47232598,  98.08434642, ...,  95.14379612,
        107.89533864,  98.84649015]])

In [111]:
def 

4.168161818296457

In [89]:
x1.prod(initial=100)

0.0

In [80]:
def k_o (s_0):
    return s_0 * np.exp((r - 0 - 0.5*(sigma1**2)) * T + sigma1 * np.sqrt(T) * x1)

In [87]:
100 * np.exp((r - 0 - 0.5*(sigma1**2)) * T + sigma1 * np.sqrt(T) * x1)

array([[ 91.87354003, 101.42121785,  95.91510448, ...,  98.86480675,
        107.42741119, 101.09606959],
       [104.20359527,  90.80284995,  93.26753579, ...,  98.47577363,
        101.17230908, 114.26955268],
       [ 95.43216872,  96.97049391,  95.08980086, ...,  92.45015272,
         98.41193156, 103.99978691],
       ...,
       [ 91.95207732,  98.20270227,  98.0154752 , ..., 101.43164397,
        105.46354898, 104.99837902],
       [ 91.71889124, 102.46133587, 105.1342564 , ..., 108.9559244 ,
        104.78297289,  97.74960125],
       [ 94.853572  ,  92.47232598,  98.08434642, ...,  95.14379612,
        107.89533864,  98.84649015]])

In [82]:
s_0 = 100
s_list = []
s_list.append(s_0)
s_t = s_0

for k in range(0 ,32+1):
    s_t = k_o(s_t)
    s_list.append(s_t)

[100,
 array([[ 91.87354003, 101.42121785,  95.91510448, ...,  98.86480675,
         107.42741119, 101.09606959],
        [104.20359527,  90.80284995,  93.26753579, ...,  98.47577363,
         101.17230908, 114.26955268],
        [ 95.43216872,  96.97049391,  95.08980086, ...,  92.45015272,
          98.41193156, 103.99978691],
        ...,
        [ 91.95207732,  98.20270227,  98.0154752 , ..., 101.43164397,
         105.46354898, 104.99837902],
        [ 91.71889124, 102.46133587, 105.1342564 , ..., 108.9559244 ,
         104.78297289,  97.74960125],
        [ 94.853572  ,  92.47232598,  98.08434642, ...,  95.14379612,
         107.89533864,  98.84649015]]),
 array([[ 84.40747358, 102.86263429,  91.99707268, ...,  97.74250015,
         115.40648675, 102.20415286],
        [108.58389267,  82.4515756 ,  86.98833233, ...,  96.97477992,
         102.35836125, 130.57530669],
        [ 91.07298826,  94.0327669 ,  90.42070228, ...,  85.47030739,
          96.84908274, 108.15955677],
       

100

In [70]:
100 * np.exp((r - 0 - 0.5*(sigma1**2)) * T + sigma1 * np.sqrt(T) * x1)[0]

array([ 91.87354003, 101.42121785,  95.91510448, 104.89590483,
        93.83544018, 108.7497698 , 103.64198645,  97.14572594,
        98.71142778,  94.18498689,  94.75713865, 102.95301237,
       103.96198629,  98.21355573, 100.57290044,  94.71669233,
        99.7101239 ,  98.98138038, 103.16049537, 105.34643385,
        99.80394867,  97.56387369,  95.32944905, 105.34134965,
       102.17339925, 103.69394955,  99.41894364, 103.2551772 ,
        99.49618602,  98.86480675, 107.42741119, 101.09606959])

In [76]:
np.random.normal(size=(num, num_time_step))[0], (rho * x1 + np.random.normal(size=(num, num_time_step)) * np.sqrt(1 - rho**2))[0]

(array([-1.45927073,  1.29774613, -0.99703709,  1.03269265,  0.38926804,
         0.96239736, -1.81054446, -1.37761194, -0.84923234,  0.3374681 ,
        -0.04814358, -2.09505462,  0.24587734, -0.1691897 , -2.218892  ,
         0.10875801,  1.55311521, -1.01621413,  0.89601532, -1.09551771,
         0.29409295, -1.91979758,  0.16432028,  2.0148979 , -1.33415539,
        -0.2397035 , -1.43407042,  0.76366465,  1.27222283,  1.60741561,
        -0.69477097, -1.02233953]),
 array([-1.01263199,  0.23588444, -0.82519378, -0.40393462,  0.74573672,
        -0.0418134 ,  1.4520525 , -1.35612123,  0.68454612,  0.44877255,
        -0.19617414, -0.9940975 ,  0.80460174,  0.60965632, -0.88925118,
         1.35825216,  0.0452629 , -0.08872449, -1.66013242,  0.86865621,
        -0.27961611,  1.50867034, -1.40674563,  1.33102517, -0.08043473,
        -0.02874245, -0.55175842,  1.37672654, -0.51580634, -1.33438424,
        -1.13714049,  2.03720755]))

In [119]:
728 / 32

22.75

In [312]:
num = 10000
num_asset = 2
num_time_step = 32
T = 22.75
r = (0.03 / 365) * 22.75
q = 0
rho = 0.2
sigma1 = 0.3
sigma2 = 0.4

st = 100

In [553]:
x1 = np.random.normal(size=(4, 1))
x2 = rho * x1 + np.random.normal(size=(4, 1)) * np.sqrt(1 - rho**2)

x1

x2

array([[0.32427369],
       [0.83610684],
       [1.34916616],
       [0.11892745]])

In [345]:
n_days = 32
div1=0 ##배당률은 0으로 가정
div2=0
r=0.05/365 #무위험 이자율
T=1 #일간 변동성을 이용하여 데이터를 만드는 것이므로 T==1
corr = 0.2
simul_data1=np.ones(n_days)
simul_data2=np.ones(n_days)
x1=np.random.normal(size=n_days)     ### 정규분포 (0,1) 생성
x2=np.random.normal(size=n_days)

e1=x1
e2=corr*x1+x2*np.sqrt(1-pow(corr,2))  ###몬테카를로 변수

###가상 데이터 생성 
simul_data1=simul_data1/np.exp((div1-r-pow(sigma1,2)/2)*T+sigma1*e1*np.sqrt(T))
simul_data2=simul_data2/np.exp((div2-r-pow(sigma2,2)/2)*T+sigma2*e2*np.sqrt(T))


In [348]:
100 * np.exp( (0.05 - 0 - 0.5 * (sigma1**2))*T + sigma1 * np.sqrt(T) * 1.76)

170.40367583907278

In [391]:
22.75 * 32

728.0

In [702]:
num = 10000
num_asset = 2
step = 32
T = 2 / step
dt = T #/num_time_step
r = 0.03 
q = 0
rho = 0.2
sigma1 = 0.3 #/ np.sqrt(step)
sigma2 = 0.4
rate = 0.125

st = 100
np.exp( (r - q - 0.5 * (sigma1**2)) * dt + sigma1 * np.sqrt(dt) * 1.7644444 ) * 100

114.0419104076519

In [518]:
a = np.ones((4, 1)) * st
a

array([[100.],
       [100.],
       [100.],
       [100.]])

In [716]:
case_dict = {
    'case1' : 100 * (1 + 0.5 * rate) / (1 + 0.5 * r),
    'case2' : 100 * (1 + 1.0 * rate) / (1 + 1.0 * r),
    'case3' : 100 * (1 + 1.5 * rate) / (1 + 1.5 * r),
    'case4' : 100 * (1 + 2.0 * rate) / (1 + 2.0 * r),
    'case5' : 100 / (1 + 2.0 * r),
    'case6' : 100 * (1 + 0.5 * rate) / (1 + 0.5 * r)
}

In [982]:
x1[:, 1].reshape(10000 ,1)

array([[1.15756407],
       [1.12427564],
       [1.20248404],
       ...,
       [1.01494491],
       [1.06778165],
       [1.09838666]])

In [988]:
num = 10000
num_asset = 2
step = 32
T = 2 / step
dt = T #/num_time_step
r = 0.03 
q = 0
rho = 0.2
sigma1 = 0.3 #/ np.sqrt(step)
sigma2 = 0.4

s1_0 = 100
s2_0 = 100
rate = 0.125

path1 = np.ones((num, 1)) * s1_0
path2 = np.ones((num, 1)) * s2_0

z1 = np.random.normal(size=(step, num)).T
z2 = rho * z1 + np.sqrt(1-rho**2) * np.random.normal(size=(step, num)).T

x1 = np.exp( (r - q - 0.5 * (sigma1 **2)) * dt + sigma1 * np.sqrt(dt) * z1)
x2 = np.exp( (r - q - 0.5 * (sigma1 **2)) * dt + sigma1 * np.sqrt(dt) * z2)

for i in range(step):
    next_path = x1[:,i].reshape(num, 1) * path1[:, -1].reshape(num, 1)
    path1 = np.c_[path1, next_path]

for i in range(step):
    next_path = x2[:,i].reshape(num, 1) * path2[:, -1].reshape(num, 1)
    path2 = np.c_[path2, next_path]


path1.shape

check1_df = pd.DataFrame(data=np.round(path1,2), index=[x for x in range(num)], columns=[x for x in range(step+1)])
check2_df = pd.DataFrame(data=np.round(path2,2), index=[x for x in range(num)], columns=[x for x in range(step+1)])

check1 = pd.DataFrame(data=np.round(path1,2), index=[[x for x in range(num)],[0 for x in range(num)]], columns=[x for x in range(step+1)])
check2 = pd.DataFrame(data=np.round(path2,2), index=[[x for x in range(num)],[1 for x in range(num)]], columns=[x for x in range(step+1)])


df = pd.concat([check1, check2]).sort_index()
df

case_list = []

for idx in range(num):
    if (check1_df[8][idx] >= 85) and (check2_df[8][idx] >= 85):
        case = 1
    elif (check1_df[16][idx] >= 80) and (check2_df[16][idx] >= 80):
        case = 2
    elif (check1_df[24][idx] >= 75) and (check2_df[24][idx] >= 75):
        case = 3 
    elif (check1_df[32][idx] >= 70) and (check2_df[32][idx] >= 70):
        case = 4

    if ((check1_df.loc[idx] < 60).sum() >= 1) or ((check2_df.loc[idx] < 60).sum() >= 1):
        if (check1_df[32][idx]< 60) or (check2_df[32][idx]< 60):
            case = 6

    if ((check1_df.loc[idx] < 60).sum() < 1) and ((check2_df.loc[idx] < 60).sum() < 1):
        if (check1_df[32][idx]< 70) or (check2_df[32][idx]< 70):
            case = 5

    case_list.append(case)
    
print((sum(np.array(case_list) == 1) / num)*100)
print((sum(np.array(case_list) == 2) / num)*100)
print((sum(np.array(case_list) == 3) / num)*100)
print((sum(np.array(case_list) == 4) / num)*100)
print((sum(np.array(case_list) == 5) / num)*100)
print((sum(np.array(case_list) == 6) / num)*100)



49.97
9.64
5.41
4.2299999999999995
7.090000000000001
23.66


In [981]:
(np.where(((check1_df[8] >= 85) * 1) * ((check2_df[8] >= 85) * 1), 1, 0)).sum()

9324

In [973]:
(check1_df[8] >= 85) * np.ones((1, len(check1_df)))

ValueError: Length of values (1) does not match length of index (10000)

In [946]:
check1

0       1       2       3       4       5       6       7       8   \
0    0  100.0  112.77  130.54  135.95  149.60  170.28  188.12  177.24  180.07   
1    0  100.0   99.05  111.37  110.14  120.40  123.97  118.97  119.74  122.49   
2    0  100.0  104.81  126.03  124.05  120.03  117.05  100.73   96.76  106.93   
3    0  100.0  103.38  114.49  119.13  110.51  117.80  114.63  116.28  132.28   
4    0  100.0   99.59   96.81   87.29   84.32   84.63   73.51   78.31   81.43   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995 0  100.0  104.31  110.54  108.15  118.60  118.24  115.81  127.92  118.11   
9996 0  100.0   97.34  104.52  122.99  127.69  120.01  135.53  125.74  113.32   
9997 0  100.0   91.59   92.96   90.25   84.06   80.40   93.33  106.46  103.08   
9998 0  100.0  110.25  117.72  111.65  123.31  125.04  122.83  108.06  108.51   
9999 0  100.0   99.05  108.80  114.66  121.12  136.56  137.63  155.50  157.44   

            9   ...      23      24      25      26      27      28      29  \
0    0  193.08  ...  279.30  311.54  275.41  274.89  283.04  298.48  306.65   
1    0  116.04  ...  200.70  231.88  246.04  228.59  241.74  240.88  241.64   
2    0  113.72  ...  166.11  171.59  189.58  198.96  173.88  165.74  186.96   
3    0  149.56  ...  156.09  151.29  157.94  163.54  155.60  150.13  139.39   
4    0   81.15  ...  112.56  107.40  115.47  121.21  119.85  121.00  123.45   
...        ...  ...     ...     ...     ...     ...     ...     ...     ...   
9995 0  127.56  ...  243.51  254.05  276.94  275.12  285.27  268.16  281.27   
9996 0  110.58  ...  172.47  210.25  227.76  228.00  199.28  191.64  204.69   
9997 0  122.01  ...  225.44  249.58  239.20  255.41  247.18  252.61  273.50   
9998 0  113.89  ...  217.98  200.94  205.58  220.93  240.90  244.40  272.42   
9999 0  164.52  ...  286.10  267.81  279.25  275.88  297.24  336.52  353.01   

            30      31      32  
0    0  326.01  343.20  311.43  
1    0  215.80  206.22  218.56  
2    0  197.57  207.60  190.84  
3    0  151.71  148.85  160.83  
4    0  110.19  108.38  109.05  
...        ...     ...     ...  
9995 0  328.51  321.09  344.14  
9996 0  207.61  223.44  215.57  
9997 0  266.02  237.81  286.64  
9998 0  321.65  325.89  336.05  
9999 0  391.32  377.63  394.60  

[10000 rows x 33 columns]

In [950]:
check1_df

0       1       2       3       4       5       6       7       8   \
0     100.0  112.77  130.54  135.95  149.60  170.28  188.12  177.24  180.07   
1     100.0   99.05  111.37  110.14  120.40  123.97  118.97  119.74  122.49   
2     100.0  104.81  126.03  124.05  120.03  117.05  100.73   96.76  106.93   
3     100.0  103.38  114.49  119.13  110.51  117.80  114.63  116.28  132.28   
4     100.0   99.59   96.81   87.29   84.32   84.63   73.51   78.31   81.43   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995  100.0  104.31  110.54  108.15  118.60  118.24  115.81  127.92  118.11   
9996  100.0   97.34  104.52  122.99  127.69  120.01  135.53  125.74  113.32   
9997  100.0   91.59   92.96   90.25   84.06   80.40   93.33  106.46  103.08   
9998  100.0  110.25  117.72  111.65  123.31  125.04  122.83  108.06  108.51   
9999  100.0   99.05  108.80  114.66  121.12  136.56  137.63  155.50  157.44   

          9   ...      23      24      25      26      27      28      29  \
0     193.08  ...  279.30  311.54  275.41  274.89  283.04  298.48  306.65   
1     116.04  ...  200.70  231.88  246.04  228.59  241.74  240.88  241.64   
2     113.72  ...  166.11  171.59  189.58  198.96  173.88  165.74  186.96   
3     149.56  ...  156.09  151.29  157.94  163.54  155.60  150.13  139.39   
4      81.15  ...  112.56  107.40  115.47  121.21  119.85  121.00  123.45   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
9995  127.56  ...  243.51  254.05  276.94  275.12  285.27  268.16  281.27   
9996  110.58  ...  172.47  210.25  227.76  228.00  199.28  191.64  204.69   
9997  122.01  ...  225.44  249.58  239.20  255.41  247.18  252.61  273.50   
9998  113.89  ...  217.98  200.94  205.58  220.93  240.90  244.40  272.42   
9999  164.52  ...  286.10  267.81  279.25  275.88  297.24  336.52  353.01   

          30      31      32  
0     326.01  343.20  311.43  
1     215.80  206.22  218.56  
2     197.57  207.60  190.84  
3     151.71  148.85  160.83  
4     110.19  108.38  109.05  
...      ...     ...     ...  
9995  328.51  321.09  344.14  
9996  207.61  223.44  215.57  
9997  266.02  237.81  286.64  
9998  321.65  325.89  336.05  
9999  391.32  377.63  394.60  

[10000 rows x 33 columns]

In [862]:
check1_df[7][0] < 85

False

In [858]:
(check2_df[7] >= 85)

0        True
1        True
2        True
3        True
4       False
        ...  
9995     True
9996     True
9997     True
9998     True
9999     True
Name: 7, Length: 10000, dtype: bool

In [871]:
32 / 4

8.0

In [893]:
for idx in range(num):
    if (check1_df.loc[idx] < 60).sum() == 1:
        print(idx)
        break

2038


In [985]:
case_list = []

for idx in range(num):
    if (check1_df[8][idx] >= 85) and (check2_df[8][idx] >= 85):
        case = 1
    elif (check1_df[16][idx] >= 80) and (check2_df[16][idx] >= 80):
        case = 2
    elif (check1_df[24][idx] >= 75) and (check2_df[24][idx] >= 75):
        case = 3 
    elif (check1_df[32][idx] >= 70) and (check2_df[32][idx] >= 70):
        case = 4

    if ((check1_df.loc[idx] < 60).sum() >= 1) or ((check2_df.loc[idx] < 60).sum() >= 1):
        if (check1_df[32][idx]< 60) or (check2_df[32][idx]< 60):
            case = 6

    if ((check1_df.loc[idx] < 60).sum() < 1) and ((check2_df.loc[idx] < 60).sum() < 1):
        if (check1_df[32][idx]< 70) or (check2_df[32][idx]< 70):
            case = 5

    case_list.append(case)
    
print(sum(np.array(case_list) == 1) / num)
print(sum(np.array(case_list) == 2) / num)
print(sum(np.array(case_list) == 3) / num)
print(sum(np.array(case_list) == 4) / num)
print(sum(np.array(case_list) == 5) / num)
print(sum(np.array(case_list) == 6) / num)


In [919]:
print(sum(np.array(case_list) == 1))
case_list[100:124]

[2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [986]:
sum(np.array(case_list) == 56

5042

=---------------------=


In [806]:
df['case'] = np.where((df[df.columns[7]] >= 85), 1, 0)

df

0       1       2       3       4       5       6       7       8  \
0    0  100.0   97.01   94.23   82.11   80.70   87.97   87.16   85.21   98.28   
     1  100.0  113.97  116.25  110.99  119.24  138.29  132.41  137.76  158.09   
1    0  100.0  119.96  135.71  142.75  132.38  132.77  132.74  144.94  125.85   
     1  100.0   97.97   87.16   84.20   98.55  118.78  116.85  132.04  131.67   
2    0  100.0   85.72   90.21   86.10   96.22   96.00   95.99   97.31   92.02   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
9997 1  100.0  103.95  109.57  100.19  104.00  109.28  124.92  123.82  119.82   
9998 0  100.0   93.98   91.48   94.83   95.45  100.08   98.19  101.83  111.41   
     1  100.0  110.75  106.80  105.05  112.47  108.67  112.94  120.06  115.27   
9999 0  100.0  106.04  111.21  119.72  110.72  130.16  134.60  137.99  125.61   
     1  100.0  101.86   98.36  108.58  101.86  114.23  129.61  127.11  128.90   

             9  ...      24      25      26      27      28      29      30  \
0    0  114.87  ...  141.73  154.17  135.62  142.78  144.13  142.98  138.61   
     1  158.17  ...  132.14  126.24  131.92  123.95  138.08  140.17  148.33   
1    0  135.95  ...  212.90  196.36  193.95  231.99  236.06  261.51  249.16   
     1  152.15  ...  146.89  139.04  147.54  163.82  174.48  182.43  189.32   
2    0   91.11  ...  158.05  149.08  153.00  159.19  141.86  139.81  137.60   
...        ...  ...     ...     ...     ...     ...     ...     ...     ...   
9997 1  104.99  ...  118.67  120.23  128.13  142.26  141.08  139.32  121.71   
9998 0  105.29  ...  167.75  174.57  166.17  176.98  180.58  173.33  196.38   
     1  125.77  ...  258.27  276.94  283.07  301.23  354.95  351.78  385.38   
9999 0  130.35  ...  207.90  213.24  244.55  233.88  237.46  238.08  254.55   
     1  135.20  ...  195.21  194.03  196.78  173.19  190.57  194.71  198.82   

            31      32  case  
0    0  134.89  132.23     1  
     1  158.05  149.23     1  
1    0  240.96  237.54     1  
     1  223.10  259.08     1  
2    0  137.37  139.93     1  
...        ...     ...   ...  
9997 1  115.61  118.86     1  
9998 0  199.17  198.25     1  
     1  382.24  376.66     1  
9999 0  243.81  243.82     1  
     1  221.17  212.84     1  

[20000 rows x 34 columns]

In [826]:
((check1[7] >= 85) * 1).sum()

9605

In [807]:
pd.pivot_table(df, index=[df.index], values='case')

case
(0, 0)        1
(0, 1)        1
(1, 0)        1
(1, 1)        1
(2, 0)        1
...         ...
(9997, 1)     1
(9998, 0)     1
(9998, 1)     1
(9999, 0)     1
(9999, 1)     1

[20000 rows x 1 columns]

In [770]:
df[(df >= 85)][df.columns[7]]

0     0     85.21
      1    137.76
1     0    144.94
      1    132.04
2     0     97.31
            ...  
9997  1    123.82
9998  0    101.83
      1    120.06
9999  0    137.99
      1    127.11
Name: 7, Length: 20000, dtype: float64

In [720]:
path1.shape

(30, 11)

In [719]:
np.c_[np.array([path1[:,3] for x in range(3)]).T, np.array(path1[:,3:])].shape

(30, 11)

In [725]:
np.ones((num, 3)) * case_dict['case1']

array([[104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980

In [740]:
condition1 = (path1[:, :3] >= s1_0 * 0.85) * np.ones((path1[:, :3].shape)) == 1


np.where(condition1, np.ones((num, 3)) * case_dict['case1'], path1[:,:3])

array([[104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296,  74.11821338],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980296, 104.67980296],
       [104.67980296, 104.67980

In [737]:
(path1[:, :3] >= s1_0 * 0.85) * np.ones((path1[:, :3].shape)) == 1


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ T

In [713]:
condition1 = (path1[:, :3] >= s1_0 * 0.85) * np.ones((path1[:, :3].shape)) == 1

np.where(condition1, np.c_[np.array([path1[:,3] for x in range(3)]).T, np.array(path1[:,3:])], path1)

ValueError: operands could not be broadcast together with shapes (30,3) (30,6) (30,6) 

In [712]:
np.where(condition)

(array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  5,  5,  5,
         6,  6,  6,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11,
        12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17,
        17, 18, 18, 18, 19, 19, 20, 21, 22, 22, 23, 23, 23, 24, 24, 25, 25,
        26, 26, 26, 27, 27, 27, 28, 29, 29, 29]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1,
        0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 1, 2, 0, 2,
        0, 2, 0, 1, 2, 0, 1, 2, 0, 0, 1, 2]))

In [701]:
100 * (1 + 0.0625 - 0.03)

103.25